config/routes.rb
Rails.application.routes.draw do
  
  resources :movies do 
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end

  resource :session, only: [:new, :create, :destroy]
  
  resources :users
  get "signup" => "users#new"
    
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/movie.rb
class Movie < ApplicationRecord

  RATINGS = %w(G PG PG-13 R NC-17)

  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :fans, through: :favorites, source: :user

  validates :title, :released_on, :duration, presence: true

  validates :description, length: { minimum: 25 }

  validates :total_gross, numericality: { greater_than: 0 }

  validates :image_file_name, format: {
    with: /\w+\.(jpg|png)\z/i,
    message: "must be a JPG or PNG image file"
  }

  validates :rating, inclusion: { in: RATINGS }

  def flop?
    total_gross.blank? || total_gross < 225_000_000
  end

  def self.released 
    where("released_on < ?", Time.now).order("released_on desc")
  end 

  def average_stars
    reviews.average(:stars) || 0.0
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
  belongs_to :user


  validates :comment, length: { minimum: 4 }

  STARS = [1, 2, 3, 4, 5]

  validates :stars, inclusion: {
    in: STARS,
    message: "must be between 1 and 5"
  }

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy  
  has_many :favorite_movies, through: :favorites, source: :movie

  validates :name, presence: true
  
  validates :email, format: { with: /\S+@\S+/ }, uniqueness: { case_sensitive: false}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

private

  def current_user
    @current_user ||=User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def require_signin
    unless current_user
      session[:intended_url] = request.url
      redirect_to new_session_url, alert: "You must be signed in to access this page."
    end
  end

  def require_admin
    unless current_user.admin?
      redirect_to movies_url, alert: "You must be an admin to access this page."
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  before_action :require_signin

  def create
    @movie = Movie.find(params[:movie_id])
    @movie.favorites.create!(user: current_user)
    redirect_to @movie
  end

  def destroy
    favorite = current_user.favorites.find(params[:id])
    favorite.destroy
    redirect_to Movie.find(params[:movie_id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

   before_action :require_signin, except: [:index, :show]
   before_action :require_admin, except: [:index, :show]

   
    def index
          @movies = Movie.released
    end

    def show 
          @movie = Movie.find(params[:id])
          @fans = @movie.fans
          if current_user
            @favorite = current_user.favorites.find_by(movie_id: @movie.id)
          end
    end

    def edit 
          @movie = Movie.find(params[:id])
    end

    def update
        @movie = Movie.find(params[:id])
        movie_params =params.require(:movie).permit(:title, :description, :rating, :released_on, :total_gross, :director, :duration, :image_file_name)
        if @movie.update(movie_params)
           redirect_to movie_path(@movie), notice: "Movie updated successfully"
        else 
           render :edit, status: :unprocessable_entity
        end
    end

    def new
        @movie = Movie.new
    end 

    def create 
      movie_params =params.require(:movie).permit(:title, :description, :rating, :released_on, :total_gross, :director, :duration, :image_file_name)
      @movie = Movie.new(movie_params)      
        if @movie.save 
           redirect_to movies_path, notice: "Movie created successfully"    
        else 
           render :new, status: :unprocessable_entity
      end
    end

    def destroy 
        @movie = Movie.find(params[:id])
        @movie.destroy
        redirect_to movies_url, status: :see_other, alert: "Movie deleted successfully"
        end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :require_signin

  def index
    @movie = Movie.find(params[:movie_id])
    @reviews = @movie.reviews
  end

  def new 
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.new
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.new(review_params)
    @review.user = current_user
    if @review.save
      redirect_to movie_reviews_url(@movie),
        notice: "Review created successfully."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def review_params
      params.require(:review).permit(:stars, :comment)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to (session[:intended_url] || user), notice: "Welcome back, #{user.name}!"
      session[:intended_url] = nil
    else
      flash.now[:alert] = "Email or password is invalid"
      render :new, status: :unprocessable_entity    
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_url, status: :see_other, notice: "Logged out successfully."
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]

def index
  @users = User.all
end

def show
  @user = User.find(params[:id])
  @reviews = @user.reviews
  @favorite_movies = @user.favorite_movies
end

def new
  @user = User.new
end

def create
  @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "User successfully created."
    else
      render :new, status: :unprocessable_entity
    end
end

def edit 
end

def update 
    if @user.update(user_params)
        redirect_to @user, notice: "Account successfully updated."
    else
        render :edit, status: :unprocessable_entity
    end
end 

def destroy
  @user.destroy
  session[:user_id] = nil if @user.id == session[:user_id]
  redirect_to movies_url, status: :see_other, alert: "Account successfully deleted."
end


private

def require_correct_user
  @user = User.find(params[:id])
  unless @user == current_user
    redirect_to movies_url, alert: "You can only edit or delete your own account."
  end
end
def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper

    def fave_or_unfave_button(movie, favorite)
      if favorite
        button_to "♡ Unfave", movie_favorite_path(movie, favorite), method: :delete
      else
        button_to "♥️ Fave", movie_favorites_path(movie)
      end
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def total_gross(movie)
    if movie.flop?
      "Flop!"
    else 
      number_to_currency(movie.total_gross)
    end
  end
   def year_of(movie)
     movie.released_on.strftime("%Y")
  end
 
end 

app/helpers/reviews_helper.rb
module ReviewsHelper

def average_stars(movie)
  if movie.average_stars.zero?
    content_tag(:strong, "No reviews")
  else
    pluralize(number_with_precision(movie.average_stars, precision: 1) , "star")
  end
end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
 <% if flash[:notice] %>
  <div class="flash notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="flash alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
  <header>
  <nav>
    <%= link_to image_tag("logo.png"), movies_path %>
    <ul class="left">
      <li>
        <%= link_to "All movies", movies_path %>
      </li>
    </ul>
    <ul class="right">
      <% if current_user %>
        <li>
           <%= link_to current_user.name, current_user %>
        </li>
        <li>
          <%= link_to "Sign Out", session_path, data: { turbo_method: :delete }, class: "button" %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign In", new_session_path, class: "button" %>
        </li>
        <li>
          <%= link_to "Sign Up", signup_path, class: "button" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Movies" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <%= render "layouts/header" %>

  <body>
    <div class="content">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>
  </body>

</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |f| %>

  <%= render "shared/errors", object: movie %>
  
  <%= f.label :title %>
  <%= f.text_field :title, autofocus: true %>

  <%= f.label :description %>
  <%= f.text_area :description, rows: 7 %>

  <%= f.label :rating %>
  <%= f.select :rating, Movie::RATINGS%>

  <%= f.label :released_on %>
  <%= f.date_field :released_on %>

  <%= f.label :total_gross %>
  <%= f.number_field :total_gross %>

  <%= f.label :director %>
  <%= f.text_field :director %>

  <%= f.label :duration %>
  <%= f.text_field :duration %>

  <%= f.label :image_file_name %> 
  <%= f.text_field :image_file_name %>

  <%= f.submit %>
<% end %>

app/views/movies/edit.html.erb
<h1> Editing Movie: <%= @movie.title %> </h1>

<%= render "form", movie: @movie%>

app/views/movies/index.html.erb
<% @movies.each do |movie| %>
  <section class="movie">
   <div class="image">
    <%= image_tag movie.image_file_name %>
  </div>
    <div class="summary">
      <h2>
        <%= link_to(movie.title, movie_path(movie)) %>
      </h2>
      <h3>
        <%= total_gross(movie) %>
      </h3>
        <span class="stars">
        <%= average_stars(movie) %>
        </span>
      <p>
        <%= truncate(movie.description, length: 150, separator: ' ') %>
      </p>
      
    </div>
  </section>
<% end %>

<% if current_user&.admin? %>
  <section class="admin">
    <%= link_to "Add New Movie", new_movie_path, class: "button" %>
  </section>
<% end %>

app/views/movies/new.html.erb
<h1>Create a New Movie</h1>

<%= render "form", movie: @movie%>

app/views/movies/show.html.erb
<section class="movie-details">
  <div class="image">
    <%= image_tag @movie.image_file_name %>
  </div>
  <% if current_user %>
  <div class="faves">
    <%= fave_or_unfave_button(@movie, @favorite) %>
    <div class="count">
      <%= @fans.size %>
    </div>
  </div>
<% end %>
  <div class="details">
    <h1><%= @movie.title %></h1>
    <h2>
      <%= year_of(@movie) %> &bull; <%= @movie.rating %>
    </h2>
    <p>
      <%= @movie.description %>
    </p>
    <table>
          <tr>
        <th>Director:</th>
        <td><%= @movie.director %></td>
      </tr>
      <tr>
        <th>Duration:</th>
        <td><%= @movie.duration %></td>
      </tr>
      <tr>
        <th>Total Gross:</th>
        <td><%= total_gross(@movie) %></td>
      </tr>
    </table>
    <div class="reviews">
      <%= average_stars(@movie) %>
        <%= link_to pluralize(@movie.reviews.size, "review"),
                movie_reviews_path(@movie) %>
      <hr/>
      <%= link_to "Review this movie", new_movie_review_path(@movie), class: "review" %>
      <p> <%= link_to "Who reviewed this movie?", movie_reviews_path(@movie) %> </p>
    </div>
  </div>
<aside>
  <% if @fans.present? %>
    <h4>Fans</h4>
    <ul>
      <% @fans.each do |user| %>
        <li>
          <%= link_to user.name, user %>
        </li>
      <% end %>
    </ul>
  <% end %>
</aside>
</section>

<% if current_user&.admin? %>
<section class="admin">
  <%= link_to "Edit", edit_movie_path(@movie), class: "button" %>
  <%= link_to "Delete", movie_path(@movie), class: "button",
         data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
</section>
<% end %>

app/views/reviews/index.html.erb
<h1>Reviews for <%= link_to @movie.title, movie_path(@movie) %></h1>
<hr>
<div class="reviews">
<% @reviews.each do |review| %>
  <p>
    <strong>Reviewer:</strong>
    <%= link_to review.user.name, review.user %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= review.comment %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= review.stars %>
  </p>
    <hr>

<% end %>
</div>

app/views/reviews/new.html.erb
<h1>Review for <%= link_to @movie.title, movie_path(@movie) %></h1>

<%= form_with(model: [@movie, @review]) do |f| %>

<%= render "shared/errors", object: @review %>

  <%= f.label :stars %>
  <%= f.number_field :stars, in: 1..5 %>

  <%= f.label :comment %>
  <%= f.text_area :comment %>

  <%= f.submit "Submit Review" %>

<% end %>
  

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section class="errors">
    <h2>
      Oops! Your form could not be saved.
    </h2>
    <h3>
      Please correct the following
      <%= pluralize(object.errors.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |f| %>

  <%= render "shared/errors", object: user %>

  <%= f.label :name %>
  <%= f.text_field :name %> 

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation %>

  <% if user.new_record? %>
    <%= f.submit "Create Account" %>
  <% else %>
  <%= f.submit "Update Account" %>
  <% end %>

<% end %>

app/views/users/edit.html.erb
<h1> Edit your profile </h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1><%= pluralize(@users.size, "User") %></h1>
<ul class="users">
  <% @users.each do |user| %>
    <li>
    <%= link_to user.name, user %> 
    created
    <%= time_ago_in_words(user.created_at) %> ago</li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<section class="user">
  <h1><%= @user.name %></h1>
  <h2><%= mail_to(@user.email) %></h2>
  <hr/>
  <div class="user-details">
  <p>Member Since</p> 
    <p><%= @user.created_at.strftime("%B %Y") %>
  </p>
  </div>
  <% if current_user == @user %>
  <div class="actions">
    <%= link_to "Edit Account", edit_user_path(@user), 
                    class:"button edit"%>
    <%= link_to "Delete Account", @user,
                data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
                class: "button delete" %> 
  </div>
  <% end %>

    <% if @reviews.present? %>
    <h3>Reviews</h3>
    <% @reviews.each do |review| %>
      <div class="review">
        <div class="details">
          <span class="title">
            <%= link_to review.movie.title, review.movie %>
          </span>
          <%= pluralize(review.stars, 'star') %>
          <span class="date">
            <%= time_ago_in_words(review.created_at) %> ago
          </span>
          <p>
            <%= review.comment %>
          </p>
        </div>
      </div>
    <% end %>
    <% if @favorite_movies.present? %>
       <h3>Favorite Movies</h3>
      <div class="favorite-movies">
        <% @favorite_movies.each do |movie| %>
          <%= link_to image_tag(movie.image_file_name), movie %>
        <% end %>
      </div>
    <% end %> 
  <% end %>
</section>